global:
  resolve_timeout: 5m

route:
  receiver: "email-alert"
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
 
receivers:
  - name: "email-alert"
    email_configs:
    - to: "cecek921@gmail.com" # Change to any email you want to send to
      from: "cangeley7@gmail.com"
      smarthost: smtp.gmail.com:587
      auth_username: "cangeley7@gmail.com"
      auth_password: "cpoqdgzqtomxbgox"
      require_tls: true